# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/programming_magic',
                'doc_host': 'https://tkinder.github.io',
                'git_url': 'https://github.com/tkinder/programming_magic',
                'lib_path': 'programming_magic'},
  'syms': {'programming_magic.core': {'programming_magic.core.foo': ('core.html#foo', 'programming_magic/core.py')}}}
